from django.db import models

# Create your models here.
class parameter(models.Model):
	sid=models.CharField(max_length=100)
	pid=models.CharField(max_length=8)
	hrmax=models.FloatField()
	hrmin=models.FloatField()
	hrmaxmin=models.FloatField()
	hrmean=models.FloatField()
	hrstd=models.FloatField()
	sbpmax=models.FloatField()
	sbpmin=models.FloatField()
	sbpmaxmin=models.FloatField()
	sbpmean=models.FloatField()
	sbpstd=models.FloatField()
	dbpmax=models.FloatField()
	dbpmin=models.FloatField()
	dbpmaxmin=models.FloatField()
	dbpmean=models.FloatField()
	dbpstd=models.FloatField()
	vpmax=models.FloatField()
	vpmin=models.FloatField()
	vpmaxmin=models.FloatField()
	vpmean=models.FloatField()
	vpstd=models.FloatField()
	apmax=models.FloatField()
	apmin=models.FloatField()
	apmaxmin=models.FloatField()
	apmean=models.FloatField()
	apstd=models.FloatField()
	ktvslope=models.FloatField()
	tbvslope=models.FloatField()
	date=models.DateTimeField(auto_now_add=True)

class Document(models.Model):
	description=models.CharField(max_length=255)
	document=models.FileField(upload_to='documents/')
	uploaded_at=models.DateTimeField(auto_now_add=True)